### ISSUE TITLE
Présentation du NLP - Qu'est ce que le NLP (Natural Language Processing) ?

### ISSUE THREAD

**Issue by MohamedBsh** [ia-z/ia-z#3]
### Sous-partie concernée

Applications

### Proposition de titre

Présentation du NLP - Qu'est ce que le NLP (Natural Language Processing) ?

### Description du cours

- Présentation de la complexité du NLP (ambiguïté, dimension, variation, distribution ..).
- Le périmètre du traitement automatique du langage - NLP (champs d'applications).
- Systèmes symboliques vs statistiques.
- Exemple de jeu de données pour les méthodes NLP statistiques.
- Pipeline de traitement des systèmes NLP statistiques.
- Vocabulaires, définitions de bases (mot, document, corpus).
-  représentations des mots (vectorisation) : BagOfWord. 
- Tf-IDF.

### Informations supplémentaires

- [X] Je peux l'écrire
- [ ] J'ai déjà du matériel
- [X] Je recherche un-une co-auteur pour : 

Implémentation Python de tf-idf/tutoriel-application avec un notebook (from scratch - scikit-learn) avec une proposition d'exercices.

**Comment by EHadoux** [comment]
Idem que sur l'autre issue 👍🏻
