### ISSUE TITLE
Recommendation de blogs, d'articles et de lectures en data science / engineering, machine learning, deep learning

### ISSUE THREAD

**Issue by MohamedBsh** [ia-z/ia-z#4]
### Sous-partie concernée

Recommandation de lectures 

### Proposition de titre

Recommandation de lectures 

### Description du cours

- condensé de blogs techniques, d'articles scientifiques, de livres par et pour la communauté Defend Intelligence.

### Informations supplémentaires

- [X] Je peux l'écrire
- [X] J'ai déjà du matériel
- [X] Je recherche un-une co-auteur

**Comment by EHadoux** [comment]
T'es garant du plan toi aussi donc tu peux faire une PR si tu veux 👍🏻
