### ISSUE TITLE
#5- Mener une recherche

### ISSUE THREAD

**Issue by Studioaxs** [ia-z/ia-z#5]
### Sous-partie concernée

Mener des recherches

### Proposition de titre

Mener une recherche internet efficacement

### Description du cours

Une introduction rapide à l'utilité de savoir mener une recherche internet correctement.
Suivie d'une liste de conseils et points clés pour bien chercher sur la toile.
2 méthodes pour mener des recherches classiques dans le cadre du cours sur les data sciences. 

Première version très simplifiée, plutôt sous forme de liste d'idées directrices que de réel cours.
Structure et mise en page à retravailler.
Version odt :
[mener_une_recherche.odt](https://github.com/ia-z/ia-z/files/7468040/mener_une_recherche.odt)

Version Markdown :
[mener_une_recherche.md](https://github.com/ia-z/ia-z/files/7468249/mener_une_recherche.md)

### Informations supplémentaires

- [X] Je peux l'écrire
- [X] J'ai déjà du matériel
- [ ] Je recherche un-une co-auteur

**Comment by EHadoux** [comment]
Y'aurait moyen que tu fasses une PR dont le contenu serait le contenu de ton fichier "mener_une_recherche.md" ? Ça permettrait de le voir en ligne directement, tu peux t'inspirer de la mienne 👍🏻

**Comment by Futurne** [comment]
Je me permet d'ajouter quelques propositions de points à aborder dans le cours. Dites moi si vous pensez que je suis hors sujet.
Fichier markdown : [notes_mener_une_recherche.md](https://github.com/ia-z/ia-z/files/7470529/notes_mener_une_recherche.md)
